<a href="https://colab.research.google.com/github/IamJac/MachineLearningAlgorithms/blob/main/LogisticRegression01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING NECCESSARY MODULES**

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report
from sklearn import datasets

**LOADING DATA**

In [3]:
wine_data = datasets.load_wine()
data=pd.DataFrame(wine_data.data,columns=wine_data.feature_names)
print("Checking if data is correctly loaded")
print(data.head())
print(data.tail())
print(data.shape)

Checking if data is correctly loaded
   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted

**EXPLORATORY DATA ANALYSIS**

In [7]:
print(data.describe())
print("Correlation of the features")
print(data.corr())
print()
print("Information of the dataset")
print(data.info())
print(data.memory_usage(deep=True))
print(wine_data.target_names)
print(wine_data.target)

          alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.9

**DATA PREPROCESSING**

In [28]:
x=data[['alcohol','malic_acid','ash','alcalinity_of_ash','magnesium','total_phenols','flavanoids','nonflavanoid_phenols','proanthocyanins','color_intensity','hue','od280/od315_of_diluted_wines','proline']].values.reshape(-1,13)
targets=pd.DataFrame(wine_data.target,columns=['target'])
y=targets['target'].values.ravel()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("Training Data")
print(x_train.shape)
print(x_train)
print()
print(y_train.shape)
print(y_train)
print()
print("Testing Data")
print(x_test.shape)
print(x_test)
print()
print(y_test.shape)
print(y_test)

Training Data
(142, 13)
[[1.434e+01 1.680e+00 2.700e+00 ... 5.700e-01 1.960e+00 6.600e+02]
 [1.253e+01 5.510e+00 2.640e+00 ... 8.200e-01 1.690e+00 5.150e+02]
 [1.237e+01 1.070e+00 2.100e+00 ... 1.040e+00 2.770e+00 6.600e+02]
 ...
 [1.438e+01 1.870e+00 2.380e+00 ... 1.200e+00 3.000e+00 1.547e+03]
 [1.269e+01 1.530e+00 2.260e+00 ... 9.600e-01 2.060e+00 4.950e+02]
 [1.234e+01 2.450e+00 2.460e+00 ... 8.000e-01 3.380e+00 4.380e+02]]

(142,)
[2 2 1 2 0 1 1 1 2 0 1 1 2 0 1 0 0 2 2 1 1 0 1 0 2 1 1 2 0 0 0 2 0 0 1 2 1
 0 2 1 0 2 1 1 0 1 0 0 1 0 0 2 1 1 1 0 1 1 1 2 2 0 1 2 2 1 1 0 1 2 2 1 2 1
 1 1 0 0 2 0 2 0 0 1 1 0 0 0 1 0 1 2 1 1 1 2 2 1 0 0 1 2 2 0 1 2 2 2 2 1 0
 1 0 2 0 0 1 0 0 2 1 0 2 2 0 0 2 2 2 1 1 1 1 1 1 2 0 1 1 0 1 1]

Testing Data
(36, 13)
[[1.364000e+01 3.100000e+00 2.560000e+00 1.520000e+01 1.160000e+02
  2.700000e+00 3.030000e+00 1.700000e-01 1.660000e+00 5.100000e+00
  9.600000e-01 3.360000e+00 8.450000e+02]
 [1.421000e+01 4.040000e+00 2.440000e+00 1.890000e+01 1.110000e+02
  2.8

**MODEL TRAINING**

In [71]:
Model=LogisticRegression(solver='saga',penalty='elasticnet',l1_ratio=0.5,C=1,max_iter=100000)
print("Model created")
Model.fit(x_train,y_train)
print("Model trained successfully")
print("Optimal Parameters obtained")
print("Weight",Model.coef_)
print("Bias=",Model.intercept_)

Model created
Model trained successfully
Optimal Parameters obtained
Weight [[-4.11613599e-02 -8.17333302e-03 -2.39873364e-04 -1.85308468e-01
  -2.23979429e-02  1.33197480e-02  4.15505254e-02 -2.77429320e-03
   8.47875469e-03 -3.44498385e-02  0.00000000e+00  2.01526929e-02
   9.08559939e-03]
 [ 2.92734344e-02 -7.84146507e-02 -2.30097800e-03  1.09230032e-01
   2.37966810e-02  3.80325891e-02  6.91710561e-02  0.00000000e+00
   3.37385549e-02 -2.05882742e-01  2.68928340e-02  7.46912226e-02
  -4.76164175e-03]
 [ 9.55060929e-03  8.89116286e-02  4.03261274e-03  7.37411024e-02
  -1.81127841e-03 -5.35467228e-02 -1.13058863e-01  3.79660137e-03
  -4.43720531e-02  2.42669984e-01 -2.59187059e-02 -9.70624014e-02
  -1.98697460e-03]]
Bias= [-0.00607109  0.00801753 -0.00194644]


**ASSESSING THE MODEL**

In [72]:
data_pred=Model.predict_proba(x_test)
data_p=pd.DataFrame(data_pred,columns=Model.classes_)
print(data_p)
predictions=Model.predict(x_test)
data1=pd.DataFrame({"Actual":y_test.squeeze(),"Predicted":predictions.squeeze(),"Probability":data_pred.max(axis=1)})
print(data1)

           0         1         2
0   0.726691  0.148787  0.124522
1   0.947679  0.016482  0.035839
2   0.040410  0.474833  0.484757
3   0.991693  0.002006  0.006301
4   0.041804  0.600808  0.357388
5   0.991010  0.002239  0.006751
6   0.062118  0.783302  0.154580
7   0.074196  0.154491  0.771313
8   0.155829  0.705232  0.138939
9   0.345440  0.160070  0.494490
10  0.585323  0.281878  0.132799
11  0.001625  0.322425  0.675950
12  0.958794  0.012682  0.028524
13  0.017633  0.628837  0.353529
14  0.996976  0.000359  0.002665
15  0.001419  0.907831  0.090750
16  0.006991  0.835360  0.157649
17  0.051583  0.740925  0.207491
18  0.972273  0.005645  0.022082
19  0.002645  0.868567  0.128788
20  0.999957  0.000001  0.000041
21  0.126949  0.539971  0.333080
22  0.299705  0.456010  0.244285
23  0.007222  0.179354  0.813424
24  0.007165  0.080740  0.912095
25  0.018031  0.077237  0.904733
26  0.000476  0.947759  0.051765
27  0.219268  0.497999  0.282733
28  0.032468  0.750829  0.216702
29  0.9444

**MODEL EVALUATION**

In [73]:
print("Model Evaluation")
print("1) Confusion Matrix")
print(confusion_matrix(y_test,predictions))
print()
print("2) Classification Report")
print(classification_report(y_test,predictions))
accuracy= (Model.score(x_test,y_test))*100
print("3) Accuracy of the model in classifying the wines=",accuracy," %")

Model Evaluation
1) Confusion Matrix
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

2) Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

3) Accuracy of the model in classifying the wines= 100.0  %
